### ISSUE TITLE
Artwork Color In Use Hint

### ISSUE THREAD

**Issue by booploops** [ciderapp/cider-themekit#4]
Place a `[theme-hint-uses-artwork-color]` type attribute on parent elements as a hint to theme stylesheets that artwork color will be used on the child elements.

Example:
```css
:not([theme-hint-uses-artwork-color]) {
  color: red;
}
```
